[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["cd asset_backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd asset_backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd asset_backend && python manage.py migrate && gunicorn asset_backend.wsgi:application --bind 0.0.0.0:$PORT"
