# Generated by Django 4.2.23 on 2025-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manual_document_data',
            field=models.BinaryField(blank=True, help_text='User manual as binary data', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manual_document_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manual_document_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manual_document_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_receipt_data',
            field=models.BinaryField(blank=True, help_text='Purchase receipt as binary data', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_receipt_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_receipt_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_receipt_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file_data',
            field=models.BinaryField(blank=True, help_text='Invoice file as binary data', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_document_data',
            field=models.BinaryField(blank=True, help_text='Warranty document as binary data', null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_document_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_document_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='warranty_document_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
    ]
