# Generated by Django 4.2.23 on 2025-09-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_backend_app', '0002_asset_manual_document_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'ordering': ['status_name'], 'verbose_name_plural': 'Asset Statuses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='depreciationmethod',
            options={'ordering': ['method_name'], 'verbose_name_plural': 'Depreciation Methods'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name'], 'verbose_name_plural': 'Vendors'},
        ),
    ]
